name: CI

on:
  # Triggers the workflow on push but only for the master branch
  push:
    branches: [ master ]
  # Triggers the workflow on any pull request
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
